[package]
name = "raylib-rs-amy"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[features]
custom_frame_control = []
support_jpeg = []

[dependencies]

[build-dependencies]
bindgen = "0.72.0"
cmake = "0.1.54"
